// import ControllerStyle from "./controller";
// import HomeStyle from "./home";
// import ListStyle from "./list";
// import LoginStyle from "./login";
// import RegisterStyle from "./register";
// import ViewerStyle from "./viewer";
// import NotfoundStyle from "./notfound";
// import MinxinsStyle from "./minxins";

export { default as ControllerStyle } from "./controller/controller";
export { default as HomeStyle } from "./home/home";
export { default as ListStyle } from "./list/list";
export { default as LoginStyle } from "./login/login";
export { default as RegisterStyle } from "./register/register";
export { default as ViewerStyle } from "./Viewer/viewer";
export { default as NotfoundStyle } from "./common/notfound";
export { default as MinxinsStyle } from "./common/minxins";
export { default as HeaderStyle } from "./home/header";
export { default as NavigationStyle } from "./common/navigation";
export { default as DetailCardStyle } from "./detailCard/detailCard";
